/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sv.edu.udb.view;



import sv.edu.udb.controller.EjemplaresDAO;
import sv.edu.udb.model.Material;
import javax.swing.*;
import java.awt.event.*;
import java.sql.Time;
import org.apache.log4j.Logger;

        

/**
 *
 * @author Mercadeo 1
 */
public class AgregarEjemplarFrame extends javax.swing.JFrame {

    private static final Logger log = Logger.getLogger(AgregarEjemplarFrame.class);
    
    private void limpiarPanelDinamico(){
        log.info("Exito al limpiar el Panel");
    pnlLibro.removeAll();
    pnlLibro.revalidate();
    pnlLibro.repaint();
    }
    
    private void mostrarPanelPorTipo(String tipo) {
    pnlLibro.setVisible(false);
    pnlRevista.setVisible(false);
    pnlTesis.setVisible(false);
    pnlCD.setVisible(false);
    pnlDocumento.setVisible(false);

    switch (tipo) {
        case "Libro":
            pnlLibro.setVisible(true);
            break;
        case "Revista":
            pnlRevista.setVisible(true);
            break;
        case "Tesis":
            pnlTesis.setVisible(true);
            break;
        case "CD":
            pnlCD.setVisible(true);
            break;
        case "Documento":
            pnlDocumento.setVisible(true);
            break;
    }

    // Para actualizar el diseño si es necesario
    this.revalidate();
    this.repaint();
}
    
   


    /**
     * Creates new form AgregarEjemplarFrame
     */
    public AgregarEjemplarFrame() {
        initComponents();
        
        setLocationRelativeTo(null);
        pnlLibro.setVisible(false);
        pnlRevista.setVisible(false);
        pnlTesis.setVisible(false);
        pnlCD.setVisible(false);
        pnlDocumento.setVisible(false);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloPanel = new javax.swing.JLabel();
        pnlPrincipal = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtAutor = new javax.swing.JTextField();
        lblUbicacion = new javax.swing.JLabel();
        lblCantidadDisponible = new javax.swing.JLabel();
        lblMaterial = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<>();
        txtUbicacion = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        pnlLibro = new javax.swing.JPanel();
        txtGenero = new javax.swing.JTextField();
        txtEditorial = new javax.swing.JTextField();
        txtPaginas = new javax.swing.JTextField();
        txtPublicacion = new javax.swing.JTextField();
        txtISBN = new javax.swing.JTextField();
        lblGenero = new javax.swing.JLabel();
        lblEditorial = new javax.swing.JLabel();
        lblPublicacion = new javax.swing.JLabel();
        lblPaginas = new javax.swing.JLabel();
        lblISBN = new javax.swing.JLabel();
        LBLNOMBRELIBROS = new javax.swing.JLabel();
        pnlRevista = new javax.swing.JPanel();
        lblVolumen = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        lblMesPublicacion = new javax.swing.JLabel();
        txtVolumen = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtMesPublicacion = new javax.swing.JTextField();
        lblCamposRevisats = new javax.swing.JLabel();
        pnlTesis = new javax.swing.JPanel();
        LBLCAMPOSTESIS = new javax.swing.JLabel();
        lblUniversidad = new javax.swing.JLabel();
        lblCarrera = new javax.swing.JLabel();
        lblPublicacionTesis = new javax.swing.JLabel();
        txtUniversidad = new javax.swing.JTextField();
        txtCarrera = new javax.swing.JTextField();
        txtPublicacionTesis = new javax.swing.JTextField();
        pnlCD = new javax.swing.JPanel();
        lblCAMPOSCD = new javax.swing.JLabel();
        lblFormato = new javax.swing.JLabel();
        lblDuracion = new javax.swing.JLabel();
        txtFormato = new javax.swing.JTextField();
        txtDuracion = new javax.swing.JTextField();
        pnlDocumento = new javax.swing.JPanel();
        lblCAMPOSDOCUMENTOS = new javax.swing.JLabel();
        lblTipoDocumento = new javax.swing.JLabel();
        lblFuente = new javax.swing.JLabel();
        txtTipoDocumento = new javax.swing.JTextField();
        txtFuente = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTituloPanel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTituloPanel.setText("Panel Agregar Ejemplares");

        lblTitulo.setText("Titulo:");

        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });

        jLabel1.setText("Autor:");

        lblUbicacion.setText("Ubicacion:");

        lblCantidadDisponible.setText("Cantidad Disponible:");

        lblMaterial.setText("Tipo Material:");

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Libro", "Revista", "Tesis", "CD", "Documento" }));
        cmbTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTipoItemStateChanged(evt);
            }
        });
        cmbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(lblUbicacion)
                            .addComponent(lblTitulo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUbicacion)
                            .addComponent(txtAutor)
                            .addComponent(txtTitulo)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlPrincipalLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMaterial)
                            .addComponent(lblCantidadDisponible))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCantidad)
                            .addComponent(cmbTipo, 0, 146, Short.MAX_VALUE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUbicacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidadDisponible)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMaterial)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnMenu.setText("Volver al Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(btnMenu)
                .addGap(28, 28, 28))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtPaginas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaginasActionPerformed(evt);
            }
        });

        lblGenero.setText("Genero:");

        lblEditorial.setText("Editorial:");

        lblPublicacion.setText("Año de Publicacion:");

        lblPaginas.setText("Numero de Paginas:");

        lblISBN.setText("ISBN:");

        LBLNOMBRELIBROS.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LBLNOMBRELIBROS.setText("CAMPOS LIBRO");

        javax.swing.GroupLayout pnlLibroLayout = new javax.swing.GroupLayout(pnlLibro);
        pnlLibro.setLayout(pnlLibroLayout);
        pnlLibroLayout.setHorizontalGroup(
            pnlLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLibroLayout.createSequentialGroup()
                .addGroup(pnlLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLibroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPublicacion)
                            .addComponent(lblEditorial)
                            .addComponent(lblGenero))
                        .addGap(18, 18, 18)
                        .addGroup(pnlLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPublicacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(56, 56, 56)
                        .addGroup(pnlLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlLibroLayout.createSequentialGroup()
                                .addComponent(lblISBN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlLibroLayout.createSequentialGroup()
                                .addComponent(lblPaginas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlLibroLayout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(LBLNOMBRELIBROS)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        pnlLibroLayout.setVerticalGroup(
            pnlLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLibroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LBLNOMBRELIBROS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGenero)
                    .addComponent(lblPaginas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEditorial)
                    .addComponent(lblISBN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPublicacion))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        lblVolumen.setText("Volumen:");

        lblNumero.setText("Numero:");

        lblMesPublicacion.setText("Mes de Publicacion:");

        lblCamposRevisats.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCamposRevisats.setText("CAMPOS REVISTAS");

        javax.swing.GroupLayout pnlRevistaLayout = new javax.swing.GroupLayout(pnlRevista);
        pnlRevista.setLayout(pnlRevistaLayout);
        pnlRevistaLayout.setHorizontalGroup(
            pnlRevistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRevistaLayout.createSequentialGroup()
                .addGroup(pnlRevistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRevistaLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(pnlRevistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNumero)
                            .addComponent(lblVolumen)))
                    .addGroup(pnlRevistaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblMesPublicacion)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRevistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCamposRevisats)
                    .addGroup(pnlRevistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtVolumen)
                        .addComponent(txtNumero)
                        .addComponent(txtMesPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        pnlRevistaLayout.setVerticalGroup(
            pnlRevistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRevistaLayout.createSequentialGroup()
                .addComponent(lblCamposRevisats)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(pnlRevistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVolumen)
                    .addComponent(txtVolumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlRevistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRevistaLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRevistaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNumero)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlRevistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMesPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMesPublicacion))
                .addContainerGap())
        );

        LBLCAMPOSTESIS.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LBLCAMPOSTESIS.setText("CAMPOS TESIS");

        lblUniversidad.setText("Universidad:");

        lblCarrera.setText("Carrera:");

        lblPublicacionTesis.setText("Año de Publicacion:");

        javax.swing.GroupLayout pnlTesisLayout = new javax.swing.GroupLayout(pnlTesis);
        pnlTesis.setLayout(pnlTesisLayout);
        pnlTesisLayout.setHorizontalGroup(
            pnlTesisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTesisLayout.createSequentialGroup()
                .addGroup(pnlTesisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTesisLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(LBLCAMPOSTESIS))
                    .addGroup(pnlTesisLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlTesisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCarrera)
                            .addComponent(lblPublicacionTesis)
                            .addComponent(lblUniversidad))
                        .addGap(18, 18, 18)
                        .addGroup(pnlTesisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUniversidad, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(txtCarrera)
                            .addComponent(txtPublicacionTesis))))
                .addContainerGap())
        );
        pnlTesisLayout.setVerticalGroup(
            pnlTesisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTesisLayout.createSequentialGroup()
                .addComponent(LBLCAMPOSTESIS)
                .addGap(18, 18, 18)
                .addGroup(pnlTesisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUniversidad)
                    .addComponent(txtUniversidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTesisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarrera)
                    .addComponent(txtCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(pnlTesisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPublicacionTesis)
                    .addComponent(txtPublicacionTesis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        lblCAMPOSCD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCAMPOSCD.setText("CAMPOS CDs");

        lblFormato.setText("Formato:");

        lblDuracion.setText("Duracion:");

        javax.swing.GroupLayout pnlCDLayout = new javax.swing.GroupLayout(pnlCD);
        pnlCD.setLayout(pnlCDLayout);
        pnlCDLayout.setHorizontalGroup(
            pnlCDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCDLayout.createSequentialGroup()
                .addGroup(pnlCDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCDLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(lblCAMPOSCD))
                    .addGroup(pnlCDLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(pnlCDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDuracion)
                            .addComponent(lblFormato))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlCDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFormato)
                            .addComponent(txtDuracion, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        pnlCDLayout.setVerticalGroup(
            pnlCDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCDLayout.createSequentialGroup()
                .addComponent(lblCAMPOSCD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFormato)
                    .addComponent(txtFormato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDuracion)
                    .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        lblCAMPOSDOCUMENTOS.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCAMPOSDOCUMENTOS.setText("CAMPOS DOCUMENTOS");

        lblTipoDocumento.setText("Tipo de Documento:");

        lblFuente.setText("Fuente:");

        javax.swing.GroupLayout pnlDocumentoLayout = new javax.swing.GroupLayout(pnlDocumento);
        pnlDocumento.setLayout(pnlDocumentoLayout);
        pnlDocumentoLayout.setHorizontalGroup(
            pnlDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDocumentoLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(lblCAMPOSDOCUMENTOS)
                .addGap(44, 44, 44))
            .addGroup(pnlDocumentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFuente)
                    .addComponent(lblTipoDocumento))
                .addGap(6, 6, 6)
                .addGroup(pnlDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTipoDocumento)
                    .addComponent(txtFuente))
                .addContainerGap())
        );
        pnlDocumentoLayout.setVerticalGroup(
            pnlDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDocumentoLayout.createSequentialGroup()
                .addComponent(lblCAMPOSDOCUMENTOS)
                .addGap(18, 18, 18)
                .addGroup(pnlDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoDocumento)
                    .addComponent(txtTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFuente)
                    .addComponent(txtFuente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlRevista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pnlTesis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pnlCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(lblTituloPanel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblTituloPanel)
                        .addGap(32, 32, 32)
                        .addComponent(pnlLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlRevista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlTesis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    private void cmbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoActionPerformed
     
    }//GEN-LAST:event_cmbTipoActionPerformed

    private void txtPaginasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaginasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaginasActionPerformed

    private void cmbTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTipoItemStateChanged
        cmbTipo.addItemListener(new ItemListener() {
    public void itemStateChanged(ItemEvent e) {
        if (e.getStateChange() == ItemEvent.SELECTED) {
            String tipoSeleccionado = (String) cmbTipo.getSelectedItem();
            mostrarPanelPorTipo(tipoSeleccionado);
        }
    }
});
    }//GEN-LAST:event_cmbTipoItemStateChanged

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
                                                 
       

String titulo = txtTitulo.getText();
String autor = txtAutor.getText();
String ubicacion = txtUbicacion.getText();
int cantidad = Integer.parseInt(txtCantidad.getText());
String tipo = cmbTipo.getSelectedItem().toString();


//Crear el objeto Material
Material material = new Material( titulo, autor, ubicacion,cantidad, tipo);
material.setTitulo(titulo);
material.setAutor(autor);
material.setUbicacion(ubicacion);
material.setCantidadDisponible(cantidad);
material.setTipo(tipo);



EjemplaresDAO dao = new EjemplaresDAO();
int idMaterial = dao.insertarMaterial(material);

if (idMaterial == -1) {
    JOptionPane.showMessageDialog(this, "Error al insertar el material base.");
    log.error("Error al insertar el material ");
    return; // detenemos si hubo error
}

switch (tipo) {
    case "Libro":
        // capturar campos específicos del libro
        String genero = txtGenero.getText();
        String editorial = txtEditorial.getText();
        int anioPublicacionLibro = Integer.parseInt(txtPublicacion.getText());
        int paginas = Integer.parseInt(txtPaginas.getText());
        String isbn = txtISBN.getText();

        boolean libroInsertado = dao.insertarLibro(idMaterial, genero, editorial, anioPublicacionLibro, paginas, isbn);
        if (!libroInsertado) {
            log.error("Error al insertar los datos del Libro ");
            JOptionPane.showMessageDialog(this, "Error al insertar los datos del libro.");
        }
        break;

    case "Revista":
        int volumen = Integer.parseInt(txtVolumen.getText());
        int numero = Integer.parseInt(txtNumero.getText());
        String mes = txtMesPublicacion.getText();

        boolean revistaInsertada = dao.insertarRevista(idMaterial, volumen, numero, mes);
        if (!revistaInsertada) {
            log.error("Error al insertar los datos de la revista ");
            JOptionPane.showMessageDialog(this, "Error al insertar los datos de la revista.");
        }
        break;

    case "Tesis":
        String universidad = txtUniversidad.getText();
        String carrera = txtCarrera.getText();
        int anioTesis = Integer.parseInt(txtPublicacionTesis.getText());

        boolean tesisInsertada = dao.insertarTesis(idMaterial, universidad, carrera, anioTesis);
        if (!tesisInsertada) {
            log.error("Error al insertar los datos de la tesis ");
            JOptionPane.showMessageDialog(this, "Error al insertar los datos de la tesis.");
        }
        break;

    case "CD":
        String formato = txtFormato.getText();
        String duracionString = txtDuracion.getText(); //  formato HH:mm:ss
        
       if (duracionString.length() == 5) {
    // agregar los segundos ":00"
    duracionString += ":00";
}

// convertir el string a Time
        try {
    Time duracion = Time.valueOf(duracionString);
    
     boolean cdInsertado = dao.insertarCD(idMaterial, formato, duracion);
    if (!cdInsertado) {
        log.error("Error al insertar los datos del CD ");
        JOptionPane.showMessageDialog(this, "Error al insertar los datos del CD.");
    }
        } catch (IllegalArgumentException e) {
            log.error("Formato de duracion es incorrecto HH:mm:ss");
        JOptionPane.showMessageDialog(this, "El formato de la duración es incorrecto. Debe ser HH:mm:ss.");
        }
        break;

    case "Documento":
        String tipoDoc = txtTipoDocumento.getText();
        String fuente = txtFuente.getText();

        boolean docInsertado = dao.insertarDocumento(idMaterial, tipoDoc, fuente);
        if (!docInsertado) {
            log.error("Error al insertar los datos del documento ");
            JOptionPane.showMessageDialog(this, "Error al insertar los datos del documento.");
        }
        break;
}
log.info("Material Agregado ccorrectamente ");
JOptionPane.showMessageDialog(this, "Material agregado correctamente.");


    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        new AdminFrame().setVisible(true);
            dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarEjemplarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarEjemplarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarEjemplarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarEjemplarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarEjemplarFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBLCAMPOSTESIS;
    private javax.swing.JLabel LBLNOMBRELIBROS;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCAMPOSCD;
    private javax.swing.JLabel lblCAMPOSDOCUMENTOS;
    private javax.swing.JLabel lblCamposRevisats;
    private javax.swing.JLabel lblCantidadDisponible;
    private javax.swing.JLabel lblCarrera;
    private javax.swing.JLabel lblDuracion;
    private javax.swing.JLabel lblEditorial;
    private javax.swing.JLabel lblFormato;
    private javax.swing.JLabel lblFuente;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblISBN;
    private javax.swing.JLabel lblMaterial;
    private javax.swing.JLabel lblMesPublicacion;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblPaginas;
    private javax.swing.JLabel lblPublicacion;
    private javax.swing.JLabel lblPublicacionTesis;
    private javax.swing.JLabel lblTipoDocumento;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloPanel;
    private javax.swing.JLabel lblUbicacion;
    private javax.swing.JLabel lblUniversidad;
    private javax.swing.JLabel lblVolumen;
    private javax.swing.JPanel pnlCD;
    private javax.swing.JPanel pnlDocumento;
    private javax.swing.JPanel pnlLibro;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlRevista;
    private javax.swing.JPanel pnlTesis;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCarrera;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtEditorial;
    private javax.swing.JTextField txtFormato;
    private javax.swing.JTextField txtFuente;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtISBN;
    private javax.swing.JTextField txtMesPublicacion;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPaginas;
    private javax.swing.JTextField txtPublicacion;
    private javax.swing.JTextField txtPublicacionTesis;
    private javax.swing.JTextField txtTipoDocumento;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtUbicacion;
    private javax.swing.JTextField txtUniversidad;
    private javax.swing.JTextField txtVolumen;
    // End of variables declaration//GEN-END:variables
}
