/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sv.edu.udb.view;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.log4j.Logger;
import sv.edu.udb.model.Prestamo;
import sv.edu.udb.controller.PrestamosDAO;

/**
 *
 * @author Mercadeo 1
 */
public class PrestamosFrame extends javax.swing.JFrame {

    private static final Logger log = Logger.getLogger(PrestamosFrame.class);
    
   private void ListarPrestamos() {
    DefaultTableModel model = new DefaultTableModel(
        new String[]{"ID Prestamo","ID Alumno","Nombre Alumno","ID Material","Titulo Material","Fecha Prestamo","Fecha Devolucion","Estado"},0
    ){
       @Override
       public boolean isCellEditable(int row, int column){
            return false;
            }
        };

    PrestamosDAO dao = new PrestamosDAO();
    List<Prestamo> lista = dao.ListarPrestamos();

    for (Prestamo p : lista) {
        model.addRow(new Object[]{
            p.getIdPrestamo(),
            p.getIdAlumno(),
            p.getNombreAlumno(),
            p.getIdMaterial(),
            p.getNombreMaterial(),
            p.getFechaPrestamo(),
            p.getFechaDevolucion(),
            p.getEstado()
        });
    }
    log.info("Prestamos listados con exito");
    tblPrestamos.setModel(model);
}

   private void limpiarCampos() {
       log.info("Se han limpiado los campos con exito");
    txtidPrestamo.setText("");
    txtidAlumno.setText("");
    txtidMaterial.setText("");
    txtFechaPrestamo.setText("");
    txtFechaDevolucion.setText("");
    cmbEstado.setSelectedIndex(0);
}

    /**
     * Creates new form PrestamosFrame
     */
    public PrestamosFrame() {
        initComponents();
        setLocationRelativeTo(null);
        ListarPrestamos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        pnlBuscarUsuarios = new javax.swing.JPanel();
        lblAlumno = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtidAlumno = new javax.swing.JTextField();
        txtidMaterial = new javax.swing.JTextField();
        txtFechaPrestamo = new javax.swing.JTextField();
        txtFechaDevolucion = new javax.swing.JTextField();
        cmbEstado = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtidPrestamo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        pnlBotones = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JButton();
        btnDevolucion = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPrestamos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setText("Gestion de Prestamos ");

        lblAlumno.setText("ID Alumno:");

        jLabel2.setText("ID Material:");

        jLabel3.setText("Fecha Prestamo:");

        jLabel4.setText("Fecha Devolucion:");

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Prestado", "Retrasado", "Devuelto" }));

        jLabel5.setText("Estado:");

        txtidPrestamo.setEditable(false);

        jLabel1.setText("ID Prestamo:");

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscar.setText("Buscar ID Alumno");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBuscarUsuariosLayout = new javax.swing.GroupLayout(pnlBuscarUsuarios);
        pnlBuscarUsuarios.setLayout(pnlBuscarUsuariosLayout);
        pnlBuscarUsuariosLayout.setHorizontalGroup(
            pnlBuscarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarUsuariosLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlBuscarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAlumno)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBuscarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtFechaDevolucion)
                    .addComponent(txtFechaPrestamo)
                    .addComponent(txtidMaterial)
                    .addComponent(txtidAlumno)
                    .addComponent(cmbEstado, 0, 171, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(pnlBuscarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBuscarUsuariosLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtidPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        pnlBuscarUsuariosLayout.setVerticalGroup(
            pnlBuscarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarUsuariosLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlBuscarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlBuscarUsuariosLayout.createSequentialGroup()
                        .addGroup(pnlBuscarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAlumno)
                            .addComponent(txtidAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtidPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2))
                    .addComponent(txtidMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBuscarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFechaPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBuscarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFechaDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlBuscarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegistrar.setText("Registar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnDevolucion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDevolucion.setText("Devolucion");
        btnDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolucionActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnListar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnMenu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMenu.setText("Volver al Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotonesLayout = new javax.swing.GroupLayout(pnlBotones);
        pnlBotones.setLayout(pnlBotonesLayout);
        pnlBotonesLayout.setHorizontalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(43, 43, 43)
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDevolucion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(81, 81, 81)
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBotonesLayout.createSequentialGroup()
                        .addComponent(btnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(47, 47, 47))
                    .addGroup(pnlBotonesLayout.createSequentialGroup()
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlBotonesLayout.setVerticalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBotonesLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlBotonesLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(23, 23, 23))
        );

        tblPrestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Prestamo", " ID Alumno", "Nombre", "ID Material", "Titulo Material", "Fecha Prestamo", "Fecha Devolucion", "Estado"
            }
        ));
        tblPrestamos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPrestamosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPrestamos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(pnlBuscarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblTitulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addComponent(pnlBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(pnlBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblTitulo)
                        .addGap(18, 18, 18)
                        .addComponent(pnlBuscarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
         try {
        Prestamo p = new Prestamo();

        // Leer valores desde los JTextField
        int idAlumno = Integer.parseInt(txtidAlumno.getText().trim());
        int idMaterial = Integer.parseInt(txtidMaterial.getText().trim());

        // Convertir fecha desde JTextField a java.util.Date
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Date fechaPrestamo = sdf.parse(txtFechaPrestamo.getText().trim());
        Date fechaDevolucion = null;
        String fechaDevText = txtFechaDevolucion.getText().trim();
            if (!fechaDevText.isEmpty()) {
            fechaDevolucion = sdf.parse(fechaDevText);
         }


        String estado = cmbEstado.getSelectedItem().toString();

        // Llenar el objeto Prestamo
        p.setIdAlumno(idAlumno);
        p.setIdMaterial(idMaterial);
        p.setFechaPrestamo(fechaPrestamo);
        p.setFechaDevolucion(fechaDevolucion);
        p.setEstado(estado);

        // Llamar al DAO
        PrestamosDAO dao = new PrestamosDAO();
        boolean registrado = dao.registrarPrestamo(p);

        if (registrado) {
            log.info("Prestamo REGISTRADO CON EXITO");
            JOptionPane.showMessageDialog(this, "Préstamo registrado correctamente.");
            ListarPrestamos(); // Refrescar tabla
        } else {
            log.error("No se puedo regiustar el prestamo");
            JOptionPane.showMessageDialog(this, "No se pudo registrar el préstamo.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    } catch (NumberFormatException e) {
        log.error("Error ID de alumno o meterial invalido"+e.getMessage());
        JOptionPane.showMessageDialog(this, "ID de alumno o material inválido.", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (ParseException e) {
        log.error("Error fecha de formato invalida Use yyyy-MM-dd."+e.getMessage());
        JOptionPane.showMessageDialog(this, "Formato de fecha inválido. Use yyyy-MM-dd.", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        log.error("Error Inesperado"+e.getMessage());
        JOptionPane.showMessageDialog(this, "Error inesperado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }   
    }//GEN-LAST:event_btnRegistrarActionPerformed

    
    
    private void btnDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolucionActionPerformed
       try {
        // Validar que hay un ID de préstamo seleccionado
        if (txtidPrestamo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seleccione un préstamo para modificar.");
           
            return;
        }

        // Crear objeto Prestamo con los datos de los campos
        Prestamo p = new Prestamo();

        p.setIdPrestamo(Integer.parseInt(txtidPrestamo.getText()));
        p.setIdAlumno(Integer.parseInt(txtidAlumno.getText()));
        p.setIdMaterial(Integer.parseInt(txtidMaterial.getText()));

        // Parsear fecha de préstamo
        Date fechaPrestamo = new SimpleDateFormat("yyyy-MM-dd").parse(txtFechaPrestamo.getText());
        p.setFechaPrestamo(fechaPrestamo);

        // Validar si la fecha de devolución está vacía
        if (txtFechaDevolucion.getText().trim().isEmpty()) {
            p.setFechaDevolucion(null);
        } else {
            Date fechaDevolucion = new SimpleDateFormat("yyyy-MM-dd").parse(txtFechaDevolucion.getText());
            p.setFechaDevolucion(fechaDevolucion);
        }

        p.setEstado(cmbEstado.getSelectedItem().toString());

        // Llamar al DAO
        PrestamosDAO dao = new PrestamosDAO();
        boolean resultado = dao.modificarPrestamo(p);

        if (resultado) {
            log.info("Préstamo modificado exitosamente");
            JOptionPane.showMessageDialog(this, "Préstamo modificado exitosamente.");
            ListarPrestamos();
            limpiarCampos();
        } else {
            log.error("No se puedo modificar el prestamo");
            JOptionPane.showMessageDialog(this, "No se pudo modificar el préstamo.");
        }

    } catch (Exception e) {
        log.error("Error: "+e.getMessage());
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_btnDevolucionActionPerformed

    
    
    private void tblPrestamosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPrestamosMouseClicked
      int fila = tblPrestamos.rowAtPoint(evt.getPoint());

    // Asegúrate que se haya seleccionado una fila válida
    if (fila >= 0) {
       txtidPrestamo.setText(tblPrestamos.getValueAt(fila, 0).toString());
        txtidAlumno.setText(tblPrestamos.getValueAt(fila, 1).toString());
        txtidMaterial.setText(tblPrestamos.getValueAt(fila, 3).toString());
        txtFechaPrestamo.setText(tblPrestamos.getValueAt(fila, 5).toString());

        // Validar que la fechaDevolución no esté vacía
        Object fechaDev = tblPrestamos.getValueAt(fila, 6);
        if (fechaDev != null) {
            txtFechaDevolucion.setText(fechaDev.toString());
        } else {
            txtFechaDevolucion.setText(""); // o "---"
        }

        cmbEstado.setSelectedItem(tblPrestamos.getValueAt(fila, 5).toString());
    }
    }//GEN-LAST:event_tblPrestamosMouseClicked

    
    
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // Validar que se haya seleccionado un préstamo
    if (txtidPrestamo.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Seleccione un préstamo de la tabla para eliminar.");
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(this, "¿Está seguro de eliminar este préstamo?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        try {
            int idPrestamo = Integer.parseInt(txtidPrestamo.getText());
            PrestamosDAO dao = new PrestamosDAO();
            boolean resultado = dao.eliminarPrestamo(idPrestamo);

            if (resultado) {
                log.info("Prestamo elimidado con exito");
                JOptionPane.showMessageDialog(this, "Préstamo eliminado exitosamente.");
                ListarPrestamos();
                limpiarCampos();
            } else {
                log.error("No se pudo eliminar el préstamo");
                JOptionPane.showMessageDialog(this, "No se pudo eliminar el préstamo.");
            }
        } catch (NumberFormatException e) {
            log.error("ID de préstamo inválido");
            JOptionPane.showMessageDialog(this, "ID de préstamo inválido.");
        }
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        ListarPrestamos();
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
          String texto = txtidAlumno.getText().trim();
    if (texto.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese el ID del alumno para buscar.");
        return;
    }

    try {
        int idAlumno = Integer.parseInt(texto);
        PrestamosDAO dao = new PrestamosDAO();
        List<Prestamo> lista = dao.buscarPrestamosPorAlumno(idAlumno);

        DefaultTableModel model = (DefaultTableModel) tblPrestamos.getModel();
        model.setRowCount(0); // limpiar tabla

        for (Prestamo p : lista) {
            model.addRow(new Object[]{
                p.getIdPrestamo(),
                p.getIdAlumno(),
                p.getNombreAlumno(),
                p.getIdMaterial(),
                p.getNombreMaterial(),
                p.getFechaPrestamo(),
                p.getFechaDevolucion(),
                p.getEstado()
            });
        }

        if (lista.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No se encontraron préstamos para ese alumno.");
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "El ID del alumno debe ser un número.");
    }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
            new AdminFrame().setVisible(true);
            dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
            limpiarCampos();        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrestamosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrestamosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrestamosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrestamosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrestamosFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnDevolucion;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAlumno;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlBuscarUsuarios;
    private javax.swing.JTable tblPrestamos;
    private javax.swing.JTextField txtFechaDevolucion;
    private javax.swing.JTextField txtFechaPrestamo;
    private javax.swing.JTextField txtidAlumno;
    private javax.swing.JTextField txtidMaterial;
    private javax.swing.JTextField txtidPrestamo;
    // End of variables declaration//GEN-END:variables
}
